<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FAQ 관리자</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
    <script src="https://unpkg.com/lucide@latest" defer></script>
    <script src="script.js" defer></script>
</head>
<body class="edit-page">
    <div class="page-container">
        <div class="content-wrapper">
            <div class="faq-container">
                <header>
                    <h1>FAQ 관리</h1>
                </header>
                
                <main id="faq-list">
                    <!-- FAQ items will be dynamically generated by JavaScript -->
                </main>

                <div class="add-new-container">
                    <button id="add-faq-btn">
                        <i data-lucide="plus"></i>
                        <span>새 질문 추가</span>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://unpkg.com/lucide@latest" defer></script>
    <script src="script.js" defer></script>
</body>
</html> 